<?php /** @var \Rl\Wordpress\Block\Page\Strate $block */ ?>
<?php
$toolboxImageHelper = $this->getToolboxImageHelper();
$strate             = $this->getStrate();

$title           = !empty($strate['strate_title']) ? $strate['strate_title'] : null;
$uptitle         = !empty($strate['strate_uptitle']) ? $strate['strate_uptitle'] : null;
$image           = !empty($strate['strate_image']) ? $strate['strate_image'] : null;
$content         = !empty($strate['strate_content']) ? $strate['strate_content'] : null;
$backgroundVideo = !empty($strate['strate_video']) ? $strate['strate_video'] : null;

if(!empty($image)){
    $backgroundAlt   = !empty($image['title']) ? $image['title'] : $title;
}

$srcset =  [
            '1920x768' => '1920',
            '1280x800' => '1280',
            '640x0'  => '640',
        ];

$sizes = [];

?>

<?php if( empty($image) ) : ?>
    <div class="container-fluid">
        <div class="row container-inner u-center justify-content-center">
            <div class="col-md-8 hero__no-image">
                <?php if( $uptitle ) : ?>
                    <div class="u-overflow-hidden">
                        <span class="page-uptitle subtitle u-inline-block u-opacity-60 u-marg-b-xxs js-active-on-visible t-fade-in t-translate-down t-translate-full">
                            <?= $block->escapeHtml($uptitle); ?>
                        </span>
                    </div>
                <?php endif; ?>
                <?php if (!empty($title)) : ?>
                    <h1 class="u-overflow-hidden">
                        <span class="u-inline-block js-active-on-visible t-fade-in t-translate-down t-translate-full" data-delay="200">
                            <?= $title ?>
                        </span>
                    </h1>
                <?php endif; ?>
                <?php if (!empty($content)) : ?>
                    <div class="text">
                        <div class="u-inline-block js-active-on-visible t-fade-in t-translate-down" data-delay="500">
                            <?= $content ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="hero u-relative u-overflow-hidden js-parallax-parent-custom" data-scroll-value="-2" data-smooth="1">

        <div class="hero__bg loaded js-parallax-parent-item">
            <div class="js-image-cover-wrapper js-active-on-visible u-transition t-fade-in t-translate-up">
                <?php echo $toolboxImageHelper->getWordpressImageHtml($image, '1920x768', $srcset, $sizes, $backgroundAlt, 'lazyload loaded js-image-cover', true); ?>
            </div>
        </div>

        <?php if($backgroundVideo) : ?>
            <div class="js-image-cover-wrapper hero__bg hero__bg--video u-back">
                <div class="media__wrapper u-relative u-overflow-hidden u-transition js-image-cover js-video-player" data-videobg="1" data-width="1920" data-height="1080">
                    <video  src="<?= $backgroundVideo ?>" 
                            preload="auto" 
                            autoplay
                            muted 
                            loop
                            class="u-full-width u-relative u-transition u-transition--long js-video" id="video__hero">
                    </video>
                </div>
            </div>
        <?php endif; ?>

        <div class="hero__content container-fluid u-middle">
            <div class="row justify-content-center">
                <div class="col-md-6 u-center u-white">
                    <?php if (!empty($title)) : ?>
                        <h1 class="u-overflow-hidden">
                            <span class="u-inline-block js-active-on-visible t-fade-in t-translate-down t-translate-full" data-delay="300">
                                <?= $title ?>
                            </span>
                        </h1>
                    <?php endif; ?>
                    <?php if (!empty($content)) : ?>
                        <div class="text u-white u-pad-b-md">
                            <div class="u-inline-block js-active-on-visible t-fade-in t-translate-down" data-delay="500">
                                <?= $content ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
