<?php /** @var \Rl\Wordpress\Block\Page\Strate $block */ ?>
<?php
$toolboxImageHelper = $this->getToolboxImageHelper();
$strate     = $this->getStrate();
$pushes     = !empty($strate['push_block']) ? $strate['push_block'] : null;
$srcset =  ['640x0'  => '640'];
$sizes = [];
?>
<?php if (!empty($pushes)) : ?>
    <div class="container-fluid">
        <div class="row u-marg-t-md justify-content-between">
            <?php
                $i = 0;
                $count = count($pushes);
                foreach ($pushes as $push) :
                    $image      = !empty($push['push_image']) ? $push['push_image'] : null;
                    $title      = !empty($push['push_title']) ? $push['push_title'] : '';
                    $imgAlt     = !empty($image['title']) ? $image['title'] : $title;
                    $upTitle    = !empty($push['push_uptitle']) ? $push['push_uptitle'] : null;
                    $cta        = !empty($push['push_url']) ? $push['push_url'] : null;
                    if (!empty($cta)) {
                        $target = !empty($cta['target']) && $cta['target'] == '_blank' ? ' target="' . $cta['target'] . '" rel="noopener noreferrer"' : '';
                    }
            ?>
                <div class="col-md-<?= 12 / $count ?> <?= $count > 3 ? 'col-6' : '' ?> u-marg-b-sm--sm js-active-on-visible t-duration-1 t-fade-in t-translate-down t-duration-1" 
                     data-delay="<?= 100 + $i*2*100 ?>">
                    <div class="push u-box-1by1<?= !empty($title) || !empty($upTitle) ? ' push--overlay' : ''; ?>">
                        <?php if (!empty($cta['url'])) : ?>
                        <a href="<?= $block->cleanUrl($cta['url']); ?>" <?= isset($target) ? $target : '' ?> class="push__link">
                        <?php endif; ?>
                        <div class="js-image-cover-wrapper<?= !empty($cta) ? ' has-hover--border' : '' ?>">
                            <?php echo $toolboxImageHelper->getWordpressImageHtml($image, '640x0', $srcset, $sizes, $imgAlt, 'lazyload js-image-cover push__thumbnail u-transition', true); ?>
                            <div class="push__content u-wrapper-panel u-center u-wrapper-vertical-align">
                                <div class="u-vertical-align-inline-block push__content-inner">
                                    <?php if ($upTitle) : ?>
                                    <span class="h3 u-block u-transition"><?php echo $upTitle ?></span>
                                    <?php endif; ?>
                                    <?php if ($title) : ?>
                                    <span class="<?= $count > 3 ? 'h2' : 'h1' ?> u-block u-transition push__content__title"><?php echo $title ?></span>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php if (!empty($cta['url'])) : ?>
                        </a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php
                $i++;
                endforeach;
            ?>
        </div>
    </div>
<?php endif; ?>
