<?php /** @var \Rl\Wordpress\Block\Page\Strate $block */ ?>
<?php
$toolboxImageHelper = $this->getToolboxImageHelper();
$strate             = $this->getStrate();

$title   = !empty($strate['strate_title']) ? $strate['strate_title'] : null;
$image   = !empty($strate['strate_image']) ? $strate['strate_image'] : null;
$content = !empty($strate['strate_content']) ? $strate['strate_content'] : null;

$srcset =  [
            '1920x768' => '1920',
            '1280x800' => '1280',
            '640x0'  => '640',
        ];

$sizes = [];

?>

<?php if( empty($image) ) : ?>
    <div class="container-fluid">
        <div class="row container-inner u-center justify-content-center">
            <div class="col-md-8">
                <?php if (!empty($title)) : ?>
                    <p class="subtitle">
                        <?= $title ?>
                    </p>
                <?php endif; ?>
                <?php if (!empty($content)) : ?>
                    <div class="u-italic h2">
                        <?= $content ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="hero u-relative u-overflow-hidden js-parallax-parent" data-scroll-value="-1.25" data-smooth="1">
        <div class="hero__bg loaded js-parallax-parent-item">
            <div class="js-image-cover-wrapper js-active-on-visible u-transition t-fade-in t-translate-up">
                <?php echo $toolboxImageHelper->getWordpressImageHtml($image, '1920x768', $srcset, $sizes, 'alt', 'lazyload loaded js-image-cover', true); ?>
            </div>
        </div>
        <div class="hero__content container-fluid u-middle">
            <div class="row justify-content-end">
                <div class="col-md-6">
                    <?php if (!empty($content)) : ?>
                        <div class="u-italic h2 u-white u-pad-b-md js-active-on-visible u-transition t-fade-in t-translate-up" data-delay="300">
                            <?= $content ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
